version: "3"

services:
  node:
    image: node
    container_name: node
    build:
      context: ./
    volumes:
      - ./:/home/app/
    ports:
      - "8080:8080"
      - "8545:8545"
    tty: true

